apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpushare-device-plugin-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: xpushare-device-plugin
      app: xpushare
      name: xpushare-device-plugin-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: xpushare-device-plugin
        app: xpushare
        name: xpushare-device-plugin-ds
    spec:
      serviceAccount: xpu-device-plugin
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      #      nodeSelector:
      #  xpushare: "true"
      containers:
        - image: tizhou86/xpu-device-plugin:v1.0.4
          name: xpushare
          # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
          command:
            - xpu-device-plugin
            - -logtostderr
            - --v=5
            - --memory-unit=MiB
          #  - --reconfig-vxpu=true
          #  - --use-detail-res-name=true
          resources:
            limits:
              memory: "300Mi"
              cpu: "1"
            requests:
              memory: "300Mi"
              cpu: "1"
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/kubelet.conf
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            #allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            # mount dev to update devices in container dynnamicly when on/off sriov
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev