apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-with-device
spec:
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: test
    spec:
      schedulerName: topology-aware-scheduler
      # schedulerName: default-scheduler
      containers:
        - name: test-deployment-1-container-1
          image: tizhou86/numalign
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: [ "while true; do numalign; sleep 100000; done;" ]
          resources:
            limits:
              cpu: 2
              memory: 50Mi
              baidu.com/xpu: 1
            requests:
              cpu: 2
              memory: 50Mi
              baidu.com/xpu: 1